[package]
name = "bamcov"
version = "0.1.0"
edition = "2021"


[dependencies]
d4={ git = "https://github.com/38/d4-format" }
regex = "1.3.1"
d4-framefile = { git = "https://github.com/38/d4-format" }
rand="0.8.4"
rayon="1.1"
clap="2.33.0"
itertools="0.10.5"
